### ISSUE TITLE
google is broken :(

### ISSUE THREAD

**Issue by gprime31** [xnl-h4ck3r/webpaste#1]
![2024-02-22_10-07](https://github.com/xnl-h4ck3r/webpaste/assets/44535257/85ec22d0-6729-40a3-a1df-d4754552fc8b)

Nice Idea to bring this tool back though!
oh and github works great btw.

**Comment by gprime31** [comment]
![2024-02-22_10-11](https://github.com/xnl-h4ck3r/webpaste/assets/44535257/d34c8ceb-b802-4101-b1ac-4c67eaf522a4)

**Comment by xnl-h4ck3r** [comment]
Hey @gprime31 ! Google isn't broken, it's because the snippet removes any links with google in it because I never search for google links in google :) 
It has `!url.includes('.google')` in the snippet. Just change the snippet to this if you want to get google specifically:
```
[...document.querySelectorAll('a')].map(n => n.href).filter(url => !url.startsWith('javascript:') && url !== '');
```

**Comment by gprime31** [comment]
> Hey @gprime31 ! Google isn't broken, it's because the snippet removes any links with google in it because I never search for google links in google :) It has `!url.includes('.google')` in the snippet. Just change the snippet to this if you want to get google specifically:
> 
> ```
> [...document.querySelectorAll('a')].map(n => n.href).filter(url => !url.startsWith('javascript:') && url !== '');
> ```

Awesome as always, Thanks!
